//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginForm.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    

    public partial class User
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "FirstName is mandatory")]
        [DisplayName("First Name")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "LastName is mandatory")]
        [DisplayName("Last Name")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Gender is mandatory")]
        
        public string Gender { get; set; }
        public int Age { get; set; }

        [Required(ErrorMessage = "Email is mandatory")]
        [EmailAddress(ErrorMessage = "Please enter valid email")]
        public string Email { get; set; }

        [Required(ErrorMessage = "UserName is mandatory")]
        [DisplayName("User Name")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "Password is mandatory")]
        [RegularExpression(@"(?=.*\d)(?=.*[A-Za-z]).{5,}")]
        [DataType(DataType.Password)]
        public string PassWord { get; set; }

        [Required(ErrorMessage = "ConfirmPassword is mandatory")]
        [DisplayName("Confirm Password")]
        [DataType(DataType.Password)]
        [Compare("PassWord",ErrorMessage = "Password is not identical")]
        public string ConfirmPassword { get; set; }
    }
}
